const randomFactsList = [
        "This isn't studying; it's a frantic search for a miracle inside a slide.",
        "My study strategy is simple: aggressively scan the pages and hope for knowledge osmosis.",
        "I'm not reading, I'm just giving my slides a panic-induced stare-down.",
        "Last-minute reading is just my brain's way of converting caffeine into a 'C' grade.",
        'I call this "catch and release" studying: catch the info, release it on the exam, and forget it by lunch.',
        "The syllabus has 12 chapters; my study plan has 12 minutes.",
        "I'm reading so fast, I'm pretty sure I'm just absorbing the page numbers.",
        "I'm currently trying to download a semester's worth of data on a 2-hour battery life.",
        "If I highlight the entire slides, does that technically count as reading it?",
        "At this point, I'm not studying for the exam; I'm just reading the spoilers.",
        "My textbook is now a 'choose your own adventure' book where every choice leads to failure.",
        "I'm not studying, I'm just speed-reading the chapter summaries and praying they're comprehensive.",
        "At this point, my study plan is just to cry and read the first letter of every paragraph.",
        "I've read so much, so fast, my brain feels like it's buffering at 240p.",
        "Trying to absorb this entire textbook in one night is like trying to drink a lake with a teaspoon.",
        "Hope is my primary study material.",
        "I've officially reached the 'guess I'll just learn it during the exam' stage.",
        "My brain cells are staging a walkout in protest of this information overload.",
        "I'm pretty sure my highlighter is doing more studying than I am.",
        "Reading this fast is just practice for scrolling past terms and condi_tions.",
        "This isn't a study session, it's a knowledge lottery, and I'm hoping to hit one matching keyword.",
        "My current retention rate is about 30 seconds, which is inconvenient for a 3-hour exam.",
        "I'm just flipping pages to create a breeze; maybe the information is airborne.",
        "I'm skimming so fast, I'm just reading the prepositions and punctuation.",
        "This textbook would be a lot more helpful if it was a movie I could watch at 2x speed.",
        "I'm not memorizing; I'm just creating very, very short-term optical illusions on my retina.",
        "The only thing I've successfully learned is how to spell the professor's name.",
        "My study group has devolved into just staring at each other in mutual panic.",
        "I'm reading the table of contents and calling it an 'executive summary.'",
        "My eyes are moving, the pages are turning, but my brain checked out two hours ago.",
      ];
